services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: hass
    restart: unless-stopped
    depends_on:
      - zwave
    # Needs host network for device discovery
    network_mode: host
    privileged: true
    devices:
      - /dev/zigbee:/dev/zigbee
    volumes:
      - /mnt/storage/hass/hass:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro

  zwave:
    image: zwavejs/zwavejs2mqtt:latest
    container_name: zwave
    restart: always
    tty: true
    stop_signal: SIGINT
    devices:
      - /dev/zwave:/dev/zwave
    volumes:
      - zwavejs2mqtt:/usr/src/app/store
    environment:
      TZ: America/Los_Angeles
      SESSION_SECRET: $ZWAVE_SECRET
      ZWAVEJS_EXTERNAL_CONFIG: /usr/src/app/store/.config-db
    networks:
      - proxy
    ports:
      - 3000:3000 # HASS is on host network


  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    environment:
      TZ: America/Los_Angeles
    volumes:
      - mosquitto:/mosquitto/data
      - /mnt/storage/hass/mosquitto.conf:/mosquitto/config/mosquitto.conf

  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    network_mode: host # Necessary to access cameras on LAN
    devices:
      # Ryzen 9 graphics
      - /dev/dri/renderD128:/dev/dri/renderD128
    environment:
      # Ryzen 9 graphics
      LIBVA_DRIVER_NAME: 'radeonsi'
      # Matches env variable usage in frigate config.yml
      FRIGATE_MQTT_USER: $FRIGATE_MQTT_USER
      FRIGATE_MQTT_PASSWORD: $FRIGATE_MQTT_PASSWORD
      FRIGATE_CAM_USER: $FRIGATE_CAM_USER
      FRIGATE_BACKYARD: $FRIGATE_BACKYARD
      FRIGATE_BACKYARD_PW: $FRIGATE_BACKYARD_PW
      FRIGATE_DOORBELL: $FRIGATE_DOORBELL
      FRIGATE_DOORBELL_PW: $FRIGATE_DOORBELL_PW
      FRIGATE_FRONTYARD: $FRIGATE_FRONTYARD
      FRIGATE_FRONTYARD_PW: $FRIGATE_FRONTYARD_PW
      FRIGATE_STUDIO_PW: $FRIGATE_STUDIO_PW
      FRIGATE_BACK_HOUSE_PW: $FRIGATE_BACK_HOUSE_PW
      FRIGATE_BACK_STUDIO_PW: $FRIGATE_BACK_STUDIO_PW
      FRIGATE_FLOOD_LIGHT: $FRIGATE_FLOOD_LIGHT
      FRIGATE_FLOOD_LIGHT_PW: $FRIGATE_FLOOD_LIGHT_PW
    volumes:
      - /mnt/storage/frigate/config:/config
      - /mnt/storage/frigate/storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000

volumes:
  zwavejs2mqtt:
  mosquitto:
  frigate:

networks:
  proxy:
    external: true

