services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: hass
    restart: unless-stopped
    depends_on:
      - zwave
    # Needs host network for device discovery
    network_mode: host
    privileged: true
    devices:
      - /dev/zigbee:/dev/zigbee
    volumes:
      - /mnt/media/hass:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro

  zwave:
    image: zwavejs/zwavejs2mqtt:latest
    container_name: zwave
    restart: always
    tty: true
    stop_signal: SIGINT
    devices:
      - /dev/zwave:/dev/zwave
    volumes:
      - zwavejs2mqtt:/usr/src/app/store
    environment:
      TZ: America/Los_Angeles
      SESSION_SECRET: $ZWAVE_SECRET
      ZWAVEJS_EXTERNAL_CONFIG: /usr/src/app/store/.config-db
    networks:
      - proxy
    ports:
      - 3000:3000

volumes:
  zwavejs2mqtt:

networks:
  proxy:
    external: true

