version: '3'

services:
  backup-volumes:
    image: busybox:latest
    container_name: backup-volumes
    environment:
      - TZ=America/Los_Angeles
      # If this is supplied, it will run logic to restore data
      # Otherwise, it will back up to a folder named with the current date
      - RESTORE_DIR={$RESTORE_DIR:-"/restore"}
    command: sh /root/entrypoint.sh
    volumes:
      # Entrypoint
      - ./backup-restore.sh:/root/entrypoint.sh
      - /mnt/media/docker_backups/2024-02-06_backup:/restore
      # Backups
      - /mnt/media/docker_backups-test/:/backups
      # Existing Volumes
      - portainer_data:/sources/portainer_data
      - /home/docker/tachidesk:/sources/media_tachidesk
      - media_plex:/sources/media_plex
      - media_overseerr:/sources/media_overseerr
      - media_sonarr-low-res:/sources/media_sonarr-low-res
      - media_sonarr-4k:/sources/media_sonarr-4k
      - media_radarr-low-res:/sources/media_radarr-low-res
      - media_radarr-4k:/sources/media_radarr-4k
      - media_prowlarr:/sources/media_prowlarr
      - media_transmission-config:/sources/media_transmission-config
      - media_gluetun:/sources/media_gluetun
      - network_omada-data:/sources/network_omada-data
      - network_omada-logs:/sources/network_omada-logs
      - network_nginx-data:/sources/network_nginx-data
      - network_nginx-letsencrypt:/sources/network_nginx-letsencrypt
      - network_pihole-dnsmasq:/sources/network_pihole-dnsmasq
      - network_pihole:/sources/network_pihole

volumes:
  portainer_data:
    external: true
  media_plex:
    external: true
  media_overseerr:
    external: true
  media_sonarr-low-res:
    external: true
  media_sonarr-4k:
    external: true
  media_radarr-low-res:
    external: true
  media_radarr-4k:
    external: true
  media_prowlarr:
    external: true
  media_transmission-config:
    external: true
  media_gluetun:
    external: true
  network_omada-data:
    external: true
  network_omada-logs:
    external: true
  network_nginx-data:
    external: true
  network_nginx-letsencrypt:
    external: true
  network_pihole-dnsmasq:
    external: true
  network_pihole:
    external: true
