version: '3'

services:
  vpn:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 4567:4567 # Tachidesk
      - 9091:9091 # Transmission
    volumes:
      - gluetun:/gluetun
    environment:
      - TZ=America/Los_Angeles
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=$VPN_USERNAME
      - OPENVPN_PASSWORD=$VPN_PASSWORD
      - UPDATER_PERIOD=24h

  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    restart: always
    ports:
      - 1900:1900
      - 3005:3005
      - 9324:9324
      - 32400:32400
      - 32410:32410
      - 32412-32414:32412-32414
      - 32469:32469
    environment:
      - ADVERTISE_IP=http://192.168.0.100:32400/
      - TZ=America/Los_Angeles
      - HOME=/config
      - PLEX_GID=1000
      - PLEX_UID=1000
      - PLEX_CLAIM=$PLEX_CLAIM
    volumes:
      - plex:/config
      - /mnt/media/movies:/movies
      - /tmp:/transcode
      - /mnt/media/tv_shows:/tv_shows
      - /mnt/media/audiobooks:/audiobooks

  overseerr:
    image: linuxserver/overseerr:latest
    container_name: overseerr
    restart: always
    ports:
      - 5055:5055
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
    volumes:
      - overseerr:/config

  sonarr-low-res:
    image: linuxserver/sonarr:latest
    container_name: sonarr-low-res
    restart: always
    ports:
      - 8989:8989
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
    volumes:
      - sonarr-low-res:/config
      - /mnt/media/tv_shows:/tv_shows
      - /mnt/media/transmission:/downloads


  sonarr-4k:
    image: linuxserver/sonarr:latest
    container_name: sonarr-4k
    restart: always
    ports:
      - 8998:8989
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
    volumes:
      - sonarr-4k:/config
      - /mnt/media/tv_shows:/tv_shows
      - /mnt/media/transmission:/downloads

  radarr-low-res:
    image: linuxserver/radarr:latest
    container_name: radarr-low-res
    restart: always
    ports:
      - 7878:7878
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
    volumes:
      - radarr-low-res:/config
      - /mnt/media/transmission:/downloads
      - /mnt/media/movies:/movies

  radarr-4k:
    image: linuxserver/radarr:latest
    container_name: radarr-4k
    restart: always
    ports:
      - 7887:7878
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
    volumes:
      - radarr-4k:/config
      - /mnt/media/transmission:/downloads
      - /mnt/media/movies:/movies

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: always
    ports:
      - 9696:9696
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
    volumes:
      - prowlarr:/config

  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    restart: always
    network_mode: service:vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - USER=$TORRENT_USERNAME
      - PASS=$TORRENT_PASSWORD
    volumes:
      - transmission-config:/config
      - /mnt/media/transmission:/downloads
      - /mnt/media/transmission/watch:/watch

  unpackerr:
    image: golift/unpackerr:latest
    container_name: unpackerr
    restart: always
    environment:
      - TZ=America/Los_Angeles
      - UN_SONARR_0_URL=http://sonarr-low-res:8989
      - UN_SONARR_0_API_KEY=$SONARR_API_KEY
      - UN_SONARR_0_PATHS_0=/data/complete/sonarr-low-res
      - UN_RADARR_0_URL=http://radarr-low-res:7878
      - UN_RADARR_0_API_KEY=$RADARR_API_KEY
      - UN_RADARR_0_PATHS_0=/data/complete/radarr-low-res
    volumes:
      - /mnt/media/transmission:/data

  tachidesk:
    image: ghcr.io/suwayomi/tachidesk:stable
    container_name: tachidesk
    restart: always
    network_mode: service:vpn
    volumes:
      - /home/docker/tachidesk:/home/suwayomi/.local/share/Tachidesk

volumes:
  plex:
  overseerr:
  sonarr-low-res:
  sonarr-4k:
  radarr-low-res:
  radarr-4k:
  prowlarr:
  transmission-config:
  gluetun:
