version: '3.3'

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: always
    user: 1000:1000
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - /mnt/media/tv_shows:/tv_shows
      - /mnt/media/movies:/movies
    networks:
      - proxy
      - arr_network

  # plex:
  #   image: plexinc/pms-docker:latest
  #   container_name: plex
  #   restart: always
  #   ports:
  #     - 1900:1900
  #     - 3005:3005
  #     - 9324:9324
  #     - 32400:32400
  #     - 32410:32410
  #     - 32412-32414:32412-32414
  #     - 32469:32469
  #   environment:
  #     - TZ=America/Los_Angeles
  #     - ADVERTISE_IP=http://192.168.0.100:32400/
  #     - HOME=/config
  #     - PLEX_GID=1000
  #     - PLEX_UID=1000
  #     - PLEX_CLAIM=$PLEX_CLAIM
  #   volumes:
  #     - plex:/config
  #     - /mnt/media/movies:/movies
  #     - /tmp:/transcode
  #     - /mnt/media/tv_shows:/tv_shows
  #     - /mnt/media/audiobooks:/audiobooks
  #   networks:
  #     - proxy
  #     - arr_network
  #     - arr_network

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
    volumes:
      - sonarr:/config
      - /mnt/media/tv_shows:/tv_shows
      - /mnt/media/transmission:/downloads
    networks:
      - proxy
      - arr_network

  sonarr-4k:
    image: linuxserver/sonarr:latest
    container_name: sonarr-4k
    restart: always
    depends_on:
      - sonarr
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
    volumes:
      - sonarr-4k:/config
      - /mnt/media/tv_shows:/tv_shows
      - /mnt/media/transmission:/downloads
    networks:
      - proxy
      - arr_network

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: always
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
    volumes:
      - radarr:/config
      - /mnt/media/transmission:/downloads
      - /mnt/media/movies:/movies
    networks:
      - proxy
      - arr_network

  radarr-4k:
    image: linuxserver/radarr:latest
    container_name: radarr-4k
    restart: always
    depends_on:
      - radarr
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
    volumes:
      - radarr-4k:/config
      - /mnt/media/transmission:/downloads
      - /mnt/media/movies:/movies
    networks:
      - proxy
      - arr_network

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: always
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
    volumes:
      - prowlarr:/config
    networks:
      - proxy
      - arr_network

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    # ports:
      # - 8888:8888/tcp # HTTP proxy
      # - 8388:8388/tcp # Shadowsocks
      # - 8388:8388/udp # Shadowsocks
      # - 4567:4567 # Tachidesk
      # - 9091:9091 # Transmission
    volumes:
      - gluetun:/gluetun
    environment:
      - TZ=America/Los_Angeles
      - VPN_SERVICE_PROVIDER=$VPN_PROVIDER
      - VPN_TYPE=openvpn
      - OPENVPN_USER=$VPN_USERNAME
      - OPENVPN_PASSWORD=$VPN_PASSWORD
      - UPDATER_PERIOD=24h
    networks:
      - proxy
      - arr_network

  unpackerr:
    image: golift/unpackerr:latest
    container_name: unpackerr
    restart: always
    environment:
      - TZ=America/Los_Angeles
      - UN_SONARR_0_URL=http://sonarr:8989
      - UN_SONARR_0_API_KEY=$SONARR_LOW_RES_API_KEY
      - UN_SONARR_0_PATHS_0=/data/complete/sonarr
      - UN_RADARR_0_URL=http://radarr:7878
      - UN_RADARR_0_API_KEY=$RADARR_LOW_RES_API_KEY
      - UN_RADARR_0_PATHS_0=/data/complete/radarr
    volumes:
      - /mnt/media/transmission:/data
    networks:
      - arr_network

  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    restart: always
    network_mode: service:gluetun
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
    volumes:
      - transmission-config:/config
      - /mnt/media/transmission:/downloads
      - /mnt/media/transmission/watch:/watch

  tachidesk:
    image: ghcr.io/suwayomi/tachidesk:preview
    container_name: tachidesk
    restart: always
    network_mode: service:gluetun
    environment:
      - TZ:America/Los_Angeles
      - DOWNLOAD_AS_CBZ=true
      - WEB_UI_ENABLED=true
      - WEB_UI_FLAVOR=WebUI
      - WEB_UI_CHANNEL=preview
      - WEB_UI_UPDATE_INTERVAL=12
      - AUTO_DOWNLOAD_CHAPTERS=true
      - AUTO_DOWNLOAD_EXCLUDE_UNREAD=false
      - AUTO_DOWNLOAD_AHEAD_LIMIT=20
      - UPDATE_EXCLUDE_UNREAD=false
      - UPDATE_EXCLUDE_STARTED=false
      - UPDATE_EXCLUDE_COMPLETED=true
      - UPDATE_INTERVAL=12
      - UPDATE_MANGA_INFO=true
      - FLARESOLVERR_ENABLED=false
    volumes:
      - /home/docker/tachidesk:/home/suwayomi/.local/share/Tachidesk

volumes:
  plex:
  jellyfin-config:
  jellyfin-cache:
  overseerr:
  sonarr:
  sonarr-4k:
  radarr:
  radarr-4k:
  prowlarr:
  transmission-config:
  gluetun:

networks:
  arr_network:
  proxy:
    external: true
