version: '3.3'

services:
  omada-controller:
    image: mbentley/omada-controller:latest
    container_name: omada-controller
    restart: always
    ports:
      - 27001:27001/udp
      - 29810:29810/udp
      - 29811-29816:29811-29816
    environment:
      TZ: America/Los_Angeles
    volumes:
      - omada-data:/opt/tplink/EAPController/data
      - omada-logs:/opt/tplink/EAPController/logs
    networks:
      - proxy

  caddy:
    # TODO use my own image
    image: ghcr.io/williamjacksn/caddy-route53:latest
    container_name: caddy
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
      - 443:443/tcp
      - 443:443/udp
    environment:
      TZ: America/Los_Angeles
      ROUTE_53_ACCESS_KEY: $ROUTE_53_ACCESS_KEY
      ROUTE_53_SECRET: $ROUTE_53_SECRET
    volumes:
      - /home/docker/portainer-compose/Caddyfile:/etc/caddy/Caddyfile
      - caddy:/data
    networks:
      - proxy

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: always
    ports:
      - 53:53/tcp
      - 53:53/udp
    environment:
      TZ: America/Los_Angeles
      DNSMASQ_USER: pihole
    volumes:
      - pihole-dnsmasq:/etc/dnsmasq.d
      - pihole:/etc/pihole
    networks:
      - proxy

  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: always
    environment:
      TZ: America/Los_Angeles
      AUTHELIA_JWT_SECRET_FILE: /secrets/AUTHELIA_JWT_SECRET
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE: /secrets/LDAP_USER_PASS
      AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: /secrets/AUTHELIA_NOTIFIER_SMTP_PASSWORD
      AUTHELIA_SESSION_SECRET_FILE: /secrets/AUTHELIA_SESSION_SECRET
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /secrets/AUTHELIA_STORAGE_ENCRYPTION_KEY
    volumes:
      - authelia:/config
      - /home/docker/portainer-compose/authelia-config.yml:/config/configuration.yml
      - /home/docker/lldap/secrets:/secrets
    networks:
      - proxy

  lldap:
    image: lldap/lldap:latest
    container_name: lldap
    volumes:
      - /home/docker/lldap/data:/data
      - /home/docker/lldap/secrets:/secrets
    environment:
      UID: 0
      GID: 0
      LLDAP_JWT_SECRET_FILE: /secrets/LDAP_JWT_SECRET
      LLDAP_KEY_SEED_FILE: /secrets/LDAP_KEY_SEED
      LLDAP_LDAP_USER_PASS_FILE: /secrets/LDAP_USER_PASS
      TZ: America/Los_Angeles
      LLDAP_LDAP_BASE_DN: dc=pauld,dc=link
    networks:
      - proxy

volumes:
  authelia:
  omada-data:
  omada-logs:
  caddy:
  pihole-dnsmasq:
  pihole:
  lldap-data:
  lldap-secrets:

networks:
  proxy:
    external: true
