version: '3.3'

services:
  omada-controller:
    image: mbentley/omada-controller:latest
    container_name: omada-controller
    restart: always
    ports:
      - 27001:27001/udp
      - 29810:29810/udp
      - 29811-29816:29811-29816
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - omada-data:/opt/tplink/EAPController/data
      - omada-logs:/opt/tplink/EAPController/logs
    networks:
      - proxy

  caddy:
    # TODO use my own image
    image: ghcr.io/williamjacksn/caddy-route53:latest
    container_name: caddy
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
      - 443:443/tcp
      - 443:443/udp
    environment:
      - TZ=America/Los_Angeles
      - ROUTE_53_ACCESS_KEY=$ROUTE_53_ACCESS_KEY
      - ROUTE_53_SECRET=$ROUTE_53_SECRET
    volumes:
      - /home/docker/portainer-compose/Caddyfile:/etc/caddy/Caddyfile
      - caddy:/data
    networks:
      - proxy

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: always
    ports:
      - 53:53/tcp
      - 53:53/udp
    environment:
      - TZ=America/Los_Angeles
      - DNSMASQ_USER=pihole
    volumes:
      - pihole-dnsmasq:/etc/dnsmasq.d
      - pihole:/etc/pihole
    networks:
      - proxy

  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: always
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - /home/docker/authelia/config:/config
    networks:
      - proxy
      - ldap

  openldap:
    image: bitnami/openldap:latest
    container_name: openldap
    volumes:
      - openldap-data:/var/lib/ldap
      - openldap-config:/etc/ldap/slapd.d
    environment:
      - LDAP_ORGANISATION=example-org
      - LDAP_DOMAIN=example.org
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_CONFIG_PASSWORD=config
      - LDAP_RFC2307BIS_SCHEMA=true
      - LDAP_REMOVE_CONFIG_AFTER_SETUP=true
      - LDAP_TLS_VERIFY_CLIENT=never
    networks:
      - ldap

  openldap-ui:
    image: wheelybird/ldap-user-manager:latest
    container_name: openldap-ui
    environment:
      - LDAP_URI=ldap://openldap
      - LDAP_BASE_DN=dc=example,dc=org
      - LDAP_REQUIRE_STARTTLS=FALSE
      - LDAP_ADMINS_GROUP=admins
      - LDAP_ADMIN_BIND_DN=cn=admin,dc=example,dc=org
      - LDAP_ADMIN_BIND_PWD=admin
      - LDAP_IGNORE_CERT_ERRORS=true
      - NO_HTTPS=TRUE
      - PASSWORD_HASH=SSHA
      - SERVER_HOSTNAME=localhost:18080
    depends_on:
      - openldap
    networks:
      - ldap

volumes:
  omada-data:
  omada-logs:
  caddy:
  pihole-dnsmasq:
  pihole:
  openldap-data:
  openldap-config:

networks:
  ldap:
  proxy:
    external: true
