version: '3.3'

services:
  backup:
    image: offen/docker-volume-backup:v2
    environment:
      AWS_S3_BUCKET_NAME: paul.diloreto.backups
      AWS_ACCESS_KEY_ID: $S3_ACCESS_KEY
      AWS_SECRET_ACCESS_KEY: $S3_SECRET_KEY
    volumes:
      # Network volumes to back up
      - network_authelia:/docker-volumes/authelia:ro
      - network_omada-data:/docker-volumes/omada-data:ro
      - network_omada-logs:/docker-volumes/omada-logs:ro
      - network_caddy:/docker-volumes/caddy:ro
      - network_pihole-dnsmasq:/docker-volumes/pihole-dnsmasq:ro
      - network_pihole:/docker-volumes/pihole:ro
      - network_lldap-data:/docker-volumes/lldap-data:ro
      - network_lldap-secrets:/docker-volumes/lldap-secrets:ro
      # Media volumes to back up
      - media_jellyfin-config:/docker-volumes/jellyfin-config:ro
      - media_jellyfin-cache:/docker-volumes/jellyfin-cache:ro
      - media_jellyseerr:/docker-volumes/jellyseerr:ro
      - media_readarr:/docker-volumes/readarr:ro
      - media_speakarr:/docker-volumes/speakarr:ro
      - media_lazylibrarian:/docker-volumes/lazylibrarian:ro
      - media_sonarr:/docker-volumes/sonarr:ro
      - media_sonarr-4k:/docker-volumes/sonarr-4k:ro
      - media_radarr:/docker-volumes/radarr:ro
      - media_radarr-4k:/docker-volumes/radarr-4k:ro
      - media_prowlarr:/docker-volumes/prowlarr:ro
      - media_transmission-config:/docker-volumes/transmission-config:ro
      - media_audiobookshelf-config:/docker-volumes/audiobookshelf-config:ro
      - media_audiobookshelf-metadata:/docker-volumes/audiobookshelf-metadata:ro
      # Local backups
      - /mnt/media/backups/docker-volumes:/archive
      # Required
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  network_authelia:
    external: true
  network_omada-data:
      external: true
  network_omada-logs:
    external: true
  network_caddy:
      external: true
  network_pihole-dnsmasq:
    external: true
  network_pihole:
      external: true
  network_lldap-data:
    external: true
  network_lldap-secrets:
    external: true
  media_jellyfin-config:
    external: true
  media_jellyfin-cache:
    external: true
  media_jellyseerr:
    external: true
  media_readarr:
    external: true
  media_speakarr:
    external: true
  media_lazylibrarian:
    external: true
  media_sonarr:
    external: true
  media_sonarr-4k:
    external: true
  media_radarr:
    external: true
  media_radarr-4k:
    external: true
  media_prowlarr:
    external: true
  media_transmission-config:
    external: true
  media_audiobookshelf-config:
    external: true
  media_audiobookshelf-metadata:
    external: true
