services:
  readarr:
    image: linuxserver/readarr:develop
    container_name: readarr
    restart: unless-stopped
    environment:
      TZ: America/Los_Angeles
      PUID: 1000
      PGID: 1000
    volumes:
      - readarr:/config
      - $BASE_DIR/media:/data
    networks:
      - proxy

  speakarr:
    image: linuxserver/readarr:develop
    container_name: speakarr
    restart: unless-stopped
    environment:
      TZ: America/Los_Angeles
      PUID: 1000
      PGID: 1000
    volumes:
      - speakarr:/config
      - $BASE_DIR/media:/data
    networks:
      - proxy

  tachidesk-vpn:
    image: qmcgaw/gluetun:latest
    container_name: tachidesk-vpn
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - tachidesk-gluetun:/gluetun
    environment:
      TZ: America/Los_Angeles
      VPN_SERVICE_PROVIDER: nordvpn
      VPN_TYPE: openvpn
      OPENVPN_USER: $VPN_USERNAME
      OPENVPN_PASSWORD: $VPN_PASSWORD
      UPDATER_PERIOD: 24h
    networks:
      - proxy
      - arr_network

  tachidesk:
    image: ghcr.io/suwayomi/tachidesk:preview
    container_name: tachidesk
    restart: unless-stopped
    network_mode: service:tachidesk-vpn
    depends_on:
      - tachidesk-vpn
    environment:
      TZ: America/Los_Angeles
      DOWNLOAD_AS_CBZ: true
      WEB_UI_ENABLED: true
      WEB_UI_FLAVOR: WebUI
      WEB_UI_CHANNEL: preview
      WEB_UI_UPDATE_INTERVAL: 12
      AUTO_DOWNLOAD_CHAPTERS: true
      AUTO_DOWNLOAD_EXCLUDE_UNREAD: false
      AUTO_DOWNLOAD_AHEAD_LIMIT: 20
      UPDATE_EXCLUDE_UNREAD: false
      UPDATE_EXCLUDE_STARTED: false
      UPDATE_EXCLUDE_COMPLETED: true
      UPDATE_INTERVAL: 12
      UPDATE_MANGA_INFO: true
      FLARESOLVERR_ENABLED: true
      # Cannot use service name due to limitations with Gluetun network
      FLARESOLVERR_URL: http://172.18.0.99:8191
    volumes:
      - $BASE_DIR/tachidesk:/home/suwayomi/.local/share/Tachidesk

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    environment:
      TZ: America/Los Angeles
    networks:
      arr_network:
        # Cannot use service name due to limitations with Gluetun network
        ipv4_address: 172.18.0.99


  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped
    volumes:
      - $BASE_DIR/media/books:/books
      - audiobookshelf-config:/config
      - audiobookshelf-metadata:/metadata
    networks:
      - proxy

  calibre:
    image: linuxserver/calibre
    container_name: calibre
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - calibre-config:/config
      - calibre-plugins:/plugins
      - $BASE_DIR/media/books:/data/books
    networks:
      - proxy

  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
    depends_on:
      - calibre
    volumes:
      - calibre-web:/config
      - $BASE_DIR/media/books:/books
    networks:
      - proxy

volumes:
  readarr:
  speakarr:
  audiobookshelf-config:
  audiobookshelf-metadata:
  tachidesk-gluetun:
  calibre-config:
  calibre-plugins:
  calibre-web:

networks:
  proxy:
    external: true
  arr_network:
    external: true
