services:
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      TZ: America/Los_Angeles
      PUID: 1000
      PGID: 1000
    volumes:
      - prowlarr:/config
    networks:
      - proxy
      - arr_network

  unpackerr:
    image: golift/unpackerr:latest
    container_name: unpackerr
    restart: unless-stopped
    environment:
      TZ: America/Los_Angeles
      UN_SONARR_0_URL: http://sonarr:8989
      UN_SONARR_0_API_KEY: $SONARR_API_KEY
      UN_SONARR_0_PATHS_0: /data/downloads/complete
      UN_RADARR_0_URL: http://radarr:7878
      UN_RADARR_0_API_KEY: $RADARR_API_KEY
      UN_RADARR_0_PATHS_0: /data/downloads/complete
    volumes:
      - /mnt/storage/media/downloads:/data/downloads
    networks:
      - arr_network

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - 9092:9091 # Expose transmission-vpn
      - 8080:8080 # qbittorrent
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - gluetun:/gluetun
    environment:
      VPN_SERVICE_PROVIDER: $VPN_SERVICE_PROVIDER
      VPN_TYPE: openvpn
      OPENVPN_USER: $OPENVPN_USER
      OPENVPN_PASSWORD: $OPENVPN_PASSWORD
      VPN_PORT_FORWARDING: $VPN_PORT_FORWARDING
      VPN_PORT_FORWARDING_PROVIDER: $VPN_SERVICE_PROVIDER
    networks:
      - proxy
      - arr_network

  transmission-vpn:
    image: linuxserver/transmission:latest
    container_name: transmission-vpn
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun
    environment:
      TZ: America/Los_Angeles
      PUID: 1000
      PGID: 1000
    volumes:
      - transmission-vpn:/config
      - /mnt/storage/media/downloads:/data/downloads

  flood-vpn:
    image: jesec/flood:latest
    container_name: flood-vpn
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun
      - transmission-vpn
    command: --port 3001 --allowedpath /data/downloads
    volumes:
      - flood-vpn:/home/download
      - /mnt/storage/media/downloads:/data/downloads

  transmission-open:
    image: linuxserver/transmission:latest
    container_name: transmission-open
    restart: unless-stopped
    environment:
      TZ: America/Los_Angeles
      PUID: 1000
      PGID: 1000
    ports:
      - 9091:9091
      - 51413:51413 # Port forwarding for seeding
    volumes:
      - transmission-open:/config
      - /mnt/storage/media/downloads:/data/downloads
    networks:
      - proxy
      - arr_network

  flood-open:
    image: jesec/flood:latest
    container_name: flood-open
    restart: unless-stopped
    command: --port 3001 --allowedpath /data/downloads
    depends_on:
      - transmission-open
    volumes:
      - flood-open:/home/download
      - /mnt/storage/media/downloads:/data/downloads
    networks:
      - proxy
      - arr_network

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent-vpn
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun
    volumes:
      - qbittorrent-vpn:/config
      - /mnt/storage/media/vuetorrent:/vuetorrent
      - /mnt/storage/media/downloads:/data/downloads


volumes:
  prowlarr:
  gluetun:
  transmission-vpn:
  flood-vpn:
  transmission-open:
  flood-open:
  qbittorrent-vpn:

networks:
  arr_network:
    external: true
  proxy:
    external: true
