theme: dark
server:
  host: 0.0.0.0
  port: 9191
log:
  level: info
default_redirection_url: https://auth.ext.pauld.link
regulation:
  max_retries: 5
  find_time: 2m
  ban_time: 10m

storage:
  local:
    path: /data/db.sqlite3

totp:
  issuer: ext.pauld.link
  period: 30
  skew: 1

authentication_backend:
  password_reset:
    disable: false
  ldap:
    implementation: custom
    url: ldap://lldap:3890
    timeout: 5s
    start_tls: false
    base_dn: DC=pauld,DC=link
    additional_users_dn: OU=people
    username_attribute: uid
    users_filter: (&({username_attribute}={input})(objectClass=person))
    mail_attribute: mail
    display_name_attribute: display_name
    additional_groups_dn: OU=groups
    groups_filter: (&(member={dn})(objectClass=groupOfNames))
    group_name_attribute: cn
    permit_referrals: false
    permit_unauthenticated_bind: false
    user: uid=admin,ou=people,dc=pauld,dc=link
access_control:
  default_policy: deny
  rules:
    - domain:
        - auth.ext.pauld.link
        - jellyfin.ext.pauld.link
        - hass.ext.pauld.link
      policy: bypass
    - domain:
        - jellyseerr.ext.pauld.link
      policy: one_factor
      subject:
        - 'group:watchers'
    - domain:
        - audiobookshelf.ext.pauld.link
        - comics.ext.pauld.link
        - readarr.ext.pauld.link
        - speakarr.ext.pauld.link
        - lib.ext.pauld.link
        - sonarr.ext.pauld.link
        - radarr.ext.pauld.link
        - lidarr.ext.pauld.link
        - prowlarr.ext.pauld.link
        - torrent.ext.pauld.link
      policy: one_factor
      subject:
        - 'group:media_admins'
    - domain:
        - calibre.ext.pauld.link
        - calibreweb.ext.pauld.link
        - ldap.ext.pauld.link
        - pihole.ext.pauld.link
        - omada.ext.pauld.link
        - portainer.ext.pauld.link
        - proxmox.ext.pauld.link
        - zwave.ext.pauld.link
      policy: two_factor
      subject:
        - 'group:admins'
         
session:
  name: authelia_session
  expiration: 3600 # 1 hour
  inactivity: 7200 # 2 hours
  domain: ext.pauld.link # Needs to be your root domain
    
notifier:
  smtp:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    sender: auth@pauld.link
