theme: dark
server:
  address: 0.0.0.0:9191
log:
  level: info
regulation:
  max_retries: 5
  find_time: 2m
  ban_time: 10m

default_redirection_url: https://auth.ext.pauld.link

# storage:
#   local:
#     path: AUTHELIA_STORAGE_LOCAL_PATH

# totp:
#   issuer: AUTHELIA_TOTP_ISSUER

authentication_backend:
  password_reset:
    disable: false

identity_providers:
  oidc:
    jwks:
      - algorithm: 'RS256'
        use: 'sig'
        key: |
          {{ secret "/secrets/key.pem" | mindent 10 "|" | msquote }}
        certificate_chain: |
          {{ secret "/secrets/cert.pem" | mindent 10 "|" | msquote }}
    clients:
      - client_id: 'portainer'
        client_name: 'Portainer'
        client_secret: '{{ secret "/secrets/OIDC_PORTAINER_SECRET" }}'
        public: false
        authorization_policy: 'two_factor'
        redirect_uris:
          - 'https://portainer.ext.pauld.link/user/oauth2/authelia/callback'
        scopes:
          - 'openid'
          - 'email'
          - 'profile'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_basic'
        jwks_uri: https://auth.ext.pauld.link/jwks.json

access_control:
  default_policy: two_factor
  rules:
    - domain:
        - auth.ext.pauld.link
        - jf.ext.pauld.link
        - jf.pauld.link
        - jellyfin.ext.pauld.link
        - jellyfin.pauld.link
        - hass.ext.pauld.link
        - hass.pauld.link
      policy: bypass
    - domain:
        - jellyseerr.ext.pauld.link
        - jellyseerr.pauld.link
      policy: one_factor
      subject:
        - 'group:watchers'
    - domain:
        - audiobookshelf.ext.pauld.link
        - audiobookshelf.pauld.link
        - comics.ext.pauld.link
        - comics.pauld.link
        - readarr.ext.pauld.link
        - readarr.pauld.link
        - speakarr.ext.pauld.link
        - speakarr.pauld.link
        - lib.ext.pauld.link
        - lib.pauld.link
        - sonarr.ext.pauld.link
        - sonarr.pauld.link
        - radarr.ext.pauld.link
        - radarr.pauld.link
        - lidarr.ext.pauld.link
        - lidarr.pauld.link
        - prowlarr.ext.pauld.link
        - prowlarr.pauld.link
        - qb.ext.pauld.link
        - qb.pauld.link
        - calibre.ext.pauld.link
        - calibre.pauld.link
        - calibreweb.ext.pauld.link
        - calibreweb.pauld.link
      policy: one_factor
      subject:
        - 'group:media_admins'
    - domain:
        - ldap.ext.pauld.link
        - ldap.pauld.link
        - pihole.ext.pauld.link
        - pihole.pauld.link
        - portainer.ext.pauld.link
        - portainer.pauld.link
        - proxmox.ext.pauld.link
        - proxmox.pauld.link
        - zwave.ext.pauld.link
        - zwave.pauld.link
        - frigate.ext.pauld.link
        - frigate.pauld.link
      policy: two_factor
      subject:
        - 'group:admins'
         
session:
  name: authelia_session
  expiration: 3600 # 1 hour
  inactivity: 7200 # 2 hours
  domain: pauld.link
    
# notifier:
#   smtp:
#     address: AUTHELIA_NOTIFIER_SMTP_ADDRESS
#     username: AUTHELIA_NOTIFIER_SMTP_USERNAME
#     sender: AUTHELIA_NOTIFIER_SMTP_SENDER
