version: '3.3'

services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: always
    environment:
      TZ: America/Los_Angeles
      AUTHELIA_JWT_SECRET_FILE: /secrets/AUTHELIA_JWT_SECRET
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE: /secrets/LDAP_USER_PASS
      AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: /secrets/AUTHELIA_NOTIFIER_SMTP_PASSWORD
      AUTHELIA_SESSION_SECRET_FILE: /secrets/AUTHELIA_SESSION_SECRET
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /secrets/AUTHELIA_STORAGE_ENCRYPTION_KEY
    volumes:
      - authelia:/config
      - /home/docker/portainer-compose/network/configs/authelia-config.yml:/config/configuration.yml
      - /home/docker/lldap/secrets:/secrets
    networks:
      - proxy

  lldap:
    image: lldap/lldap:latest
    container_name: lldap
    volumes:
      - /home/docker/lldap/data:/data
      - /home/docker/lldap/secrets:/secrets
    environment:
      UID: 0
      GID: 0
      LLDAP_JWT_SECRET_FILE: /secrets/LDAP_JWT_SECRET
      LLDAP_KEY_SEED_FILE: /secrets/LDAP_KEY_SEED
      LLDAP_LDAP_USER_PASS_FILE: /secrets/LDAP_USER_PASS
      TZ: America/Los_Angeles
      LLDAP_LDAP_BASE_DN: dc=pauld,dc=link
    networks:
      - proxy

volumes:
  authelia:
  lldap-data:
  lldap-secrets:

networks:
  proxy:
    external: true
