services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: always
    environment:
      TZ: $TZ
      X_AUTHELIA_CONFIG_FILTERS: template
      AUTHELIA_TOTP_ISSUER: $AUTHELIA_TOTP_ISSUER
      AUTHELIA_STORAGE_LOCAL_PATH: $AUTHELIA_STORAGE_LOCAL_PATH
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ADDRESS: $AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ADDRESS
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_IMPLEMENTATION: $AUTHELIA_AUTHENTICATION_BACKEND_LDAP_IMPLEMENTATION
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ADDITIONAL_USERS_DN: $AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ADDITIONAL_USERS_DN
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USER: $AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USER
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_BASE_DN: $AUTHELIA_AUTHENTICATION_BACKEND_LDAP_BASE_DN
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ATTRIBUTES_USERNAME: $AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ATTRIBUTES_USERNAME
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USERS_FILTER: $AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USERS_FILTER
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ATTRIBUTES_MAIL: $AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ATTRIBUTES_MAIL
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ATTRIBUTES_DISPLAY_NAME: $AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ATTRIBUTES_DISPLAY_NAME
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ADDITIONAL_GROUPS_DN: $AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ADDITIONAL_GROUPS_DN
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_GROUPS_FILTER: $AUTHELIA_AUTHENTICATION_BACKEND_LDAP_GROUPS_FILTER
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ATTRIBUTES_GROUP_NAME: $AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ATTRIBUTES_GROUP_NAME
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_TIMEOUT: $AUTHELIA_AUTHENTICATION_BACKEND_LDAP_TIMEOUT
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_START_TLS: $AUTHELIA_AUTHENTICATION_BACKEND_LDAP_START_TLS
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PERMIT_REFERRALS: $AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PERMIT_REFERRALS
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PERMIT_UNAUTHENTICATED_BIND: $AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PERMIT_UNAUTHENTICATED_BIND
      AUTHELIA_NOTIFIER_SMTP_ADDRESS: $AUTHELIA_NOTIFIER_SMTP_ADDRESS
      AUTHELIA_NOTIFIER_SMTP_USERNAME: $AUTHELIA_NOTIFIER_SMTP_USERNAME
      AUTHELIA_NOTIFIER_SMTP_SENDER: $AUTHELIA_NOTIFIER_SMTP_SENDER
      AUTHELIA_JWT_SECRET_FILE: $AUTHELIA_JWT_SECRET_FILE
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE: $AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE
      AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: $AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
      AUTHELIA_SESSION_SECRET_FILE: $AUTHELIA_SESSION_SECRET_FILE
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: $AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE: $AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE
    volumes:
      - authelia:/data
      - /mnt/storage/docker-compose/network/authelia-config.yml:/config/configuration.yml
      - /mnt/storage/lldap/secrets:/secrets
    networks:
      - proxy

  lldap:
    image: lldap/lldap:latest
    container_name: lldap
    restart: always
    volumes:
      - /mnt/storage/lldap/data:/data
      - /mnt/storage/lldap/secrets:/secrets
    environment:
      UID: 0
      GID: 0
      LLDAP_JWT_SECRET_FILE: /secrets/LDAP_JWT_SECRET
      LLDAP_KEY_SEED_FILE: /secrets/LDAP_KEY_SEED
      LLDAP_LDAP_USER_PASS_FILE: /secrets/LDAP_USER_PASS
      TZ: $TZ
      LLDAP_LDAP_BASE_DN: dc=pauld,dc=link
    networks:
      - proxy

volumes:
  lldap-data:
  lldap-secrets:
  authelia:

networks:
  proxy:
    external: true
