name: Workflow for main branch changes

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

  env:
    WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

  steps:
    - name: Trigger Portainer Webhook
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -d '{}' \
          $WEBHOOK_URL
